<?php
namespace DAO;
require_once '../Entidades/Auditoria/BienServiciosEntidad.php';
require_once '../Entidades/Auditoria/CuentaPucEntidad.php';
require_once '../Entidades/Auditoria/DetallePagosEntidad.php';
require_once '../Entidades/Auditoria/DocPagosEntidad.php';
require_once '../Entidades/Auditoria/DocProveedoresEntidad.php';
require_once '../Entidades/Auditoria/ImpuestoPagosEntidad.php';
require_once '../Entidades/Auditoria/MovimientoEntidad.php';
require_once '../Entidades/Auditoria/PagosEntidad.php';
require_once '../Entidades/Auditoria/ProveedoresEntidad.php';
require_once '../Entidades/Auditoria/SaldosEntidad.php';
require_once '../Entidades/Configuracion/AccesoModulosEntidad.php';
require_once '../Entidades/Configuracion/CiiuDirectorioEntidad.php';
require_once '../Entidades/Configuracion/CiiuEntidad.php';
require_once '../Entidades/Configuracion/ClientesEntidad.php';
require_once '../Entidades/Configuracion/DirectorioEntidad.php';
require_once '../Entidades/Configuracion/LugaresEntidad.php';
require_once '../Entidades/Configuracion/ModulosEntidad.php';
require_once '../Entidades/Configuracion/ParametrosEntidad.php';
require_once '../Entidades/Configuracion/RolesEntidad.php';
require_once '../Entidades/Configuracion/RolesPermisosEntidad.php';
require_once '../Entidades/Configuracion/RolesUsuariosEntidad.php';
require_once '../Entidades/Configuracion/UsuarioEntidad.php';
require_once '../Entidades/General/CorreoEntidad.php';
require_once '../Entidades/General/ModificadorTablasEntidad.php';

use Entidades\AccesoModulosEntidad;
use Entidades\BienServiciosEntidad;
use Entidades\CiiuDirectorioEntidad;
use Entidades\CiiuEntidad;
use Entidades\ClientesEntidad;
use Entidades\CorreoEntidad;
use Entidades\CuentaPucEntidad;
use Entidades\DetallePagosEntidad;
use Entidades\DirectorioEntidad;
use Entidades\DocPagosEntidad;
use Entidades\DocProveedoresEntidad;
use Entidades\ImpuestoPagosEntidad;
use Entidades\LugaresEntidad;
use Entidades\ModificadorTablasEntidad;
use Entidades\ModulosEntidad;
use Entidades\MovimientoEntidad;
use Entidades\PagosEntidad;
use Entidades\ParametrosEntidad;
use Entidades\ProveedoresEntidad;
use Entidades\RolesEntidad;
use Entidades\RolesPermisosEntidad;
use Entidades\RolesUsuariosEntidad;
use Entidades\SaldosEntidad;
use Entidades\UsuarioEntidad;

interface IDAOFacade{
	public function buscarUsuario(UsuarioEntidad $usuario);
	public function adicionarUsuario(UsuarioEntidad $usuario);
	public function modificarUsuario(UsuarioEntidad $usuario);
	public function inactivarUsuario(UsuarioEntidad $usuario);
	public function cambioClave(UsuarioEntidad $usuario);
	public function listarModulosUsuario(UsuarioEntidad $usuario); 
	public function listarModulos(ModulosEntidad $modulos);
	public function listarRoles(RolesEntidad $roles);
	public function adicionarRoles(RolesEntidad $roles);
	public function modificarRoles(RolesEntidad $roles);
	public function inactivarRoles(RolesEntidad $roles);
	public function listarRolesPermisos(RolesPermisosEntidad $rolesPermisos);
	public function adicionarRolesPermisos(RolesPermisosEntidad $rolesPermisos);
	public function modificarRolesPermisos(RolesPermisosEntidad $rolesPermisos);
	public function listarRolesUsuarios(RolesUsuariosEntidad $rolesUsuarios);
	public function adicionarRolesUsuarios(RolesUsuariosEntidad $rolesUsuarios);
	public function modificarRolesUsuarios(RolesUsuariosEntidad $rolesUsuarios);
	public function listarClientes(ClientesEntidad $clientes);
	public function adicionarClientes(ClientesEntidad $clientes);
	public function modificarClientes(ClientesEntidad $clientes);
	public function inactivarClientes(ClientesEntidad $clientes);
	public function listarProveedores(ProveedoresEntidad $proveedores);
	public function adicionarProveedores(ProveedoresEntidad $proveedores);
	public function modificarProveedores(ProveedoresEntidad $proveedores);
	public function inactivarProveedores(ProveedoresEntidad $proveedores);
	public function listarDocProveedores(DocProveedoresEntidad $docProveedores);
	public function adicionarDocProveedores(DocProveedoresEntidad $docProveedores);
	public function modificarDocProveedores(DocProveedoresEntidad $docProveedores);
	public function listarDirectorio(DirectorioEntidad $directorio);
	public function adicionarDirectorio(DirectorioEntidad $directorio);
	public function modificarDirectorio(DirectorioEntidad $directorio);
	public function inactivarDirectorio(DirectorioEntidad $Directorio);
	public function listarCiiu(CiiuEntidad $ciiu);
	public function adicionarCiiu(CiiuEntidad $ciiu);
	public function modificarCiiu(CiiuEntidad $ciiu);
	public function listarCiiuDirectorio(CiiuDirectorioEntidad $ciiuDirectorio);
	public function adicionarCiiuDirectorio(CiiuDirectorioEntidad $ciiuDirectorio);
	public function modificarCiiuDirectorio(CiiuDirectorioEntidad $ciiuDirectorio);
	public function listarParametros(ParametrosEntidad $parametros);
	public function adicionarParametros(ParametrosEntidad $parametros);
	public function modificarParametros(ParametrosEntidad $parametros);
	public function listarLugares(LugaresEntidad $lugares);
	public function adicionarLugares(LugaresEntidad $lugares);
	public function modificarLugares(LugaresEntidad $lugares);
	public function listarModificadorTablas(ModificadorTablasEntidad $modificadorTablas);
	public function ultUsuarioFechaHora(ModificadorTablasEntidad $modificadorTablas);
	public function adicionarModificadorTablas(ModificadorTablasEntidad $modificadorTablas);
	public function listarAccesoModulos(AccesoModulosEntidad $accesoModulos);
	public function adicionarAccesoModulos(AccesoModulosEntidad $accesoModulos);
	public function listarBienServicios(BienServiciosEntidad $bienServicios);
	public function adicionarBienServicios(BienServiciosEntidad $bienServicios);
	public function modificarBienServicios(BienServiciosEntidad $bienServicios);
	public function listarDetallePagos(DetallePagosEntidad $detallePagos);
	public function adicionarDetallePagos(DetallePagosEntidad $detallePagos);
	public function modificarDetallePagos(DetallePagosEntidad $detallePagos);
	public function listarDocPagos(DocPagosEntidad $docPagos);
	public function adicionarDocPagos(DocPagosEntidad $docPagos);
	public function modificarDocPagos(DocPagosEntidad $docPagos);
	public function listarImpuestoPagos(ImpuestoPagosEntidad $impuestoPagos);
	public function adicionarImpuestoPagos(ImpuestoPagosEntidad $impuestoPagos);
	public function modificarImpuestoPagos(ImpuestoPagosEntidad $impuestoPagos);
	public function listarPagos(PagosEntidad $pagos);
	public function adicionarPagos(PagosEntidad $agos);
	public function modificarPagos(PagosEntidad $pagos);
	public function enviarCorreo(CorreoEntidad $correo);
	public function listarCuentaPuc(CuentaPucEntidad $cuentaPuc);
	public function modificarCuentaPuc(CuentaPucEntidad $cuentaPuc);
	public function listarMovimiento(MovimientoEntidad $movimiento);
	public function comboMovimiento(MovimientoEntidad $movimiento);
	public function borrarMovimiento(MovimientoEntidad $movimiento);
	public function insertarMovimiento(MovimientoEntidad $movimiento);
	public function insertarMovimientoCop(MovimientoEntidad $movimiento);
	public function listarSaldos(SaldosEntidad $saldos);
	public function borrarSaldos(SaldosEntidad $saldos);
	public function insertarSaldos(SaldosEntidad $saldos);
	public function insertarSaldosCop(SaldosEntidad $saldos);
}
?>